services:
  in-order:
    build: .
    ports:
      - "4000:3000"
    depends_on:
      - db
  db:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_PORT=3306
      - MYSQL_USER=tanmay
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=mvc
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
